enum DatabaseConfig {
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PWD = 'DATABASE_PWD',
  DATABASE_NAME = 'DATABASE_NAME',
}
export { DatabaseConfig };
